name:                monty
version:             0.1.0.0
github:              "Mulan-Szechuan-Sauce/monty"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/monty#readme>

dependencies:
- base >= 4.7
- megaparsec
- unordered-containers
- hashable
- mtl
- lens
- directory
- filepath
- parser-combinators
- repline >= 0.4.0.0
- string-interpolate

library:
  source-dirs: src
  default-extensions:
    - NamedFieldPuns
    - GADTs
    - TemplateHaskell
    - QuasiQuotes

executables:
  monty-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monty

tests:
  monty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monty
    - hspec
    - QuickCheck
    - silently
